config/routes.rb
Rails.application.routes.draw do
  get 'artists/', to: 'artists#index'
  get 'artists/:id', to: 'artists#show', as: 'artist'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find params[:id]
    @albums = Album.where(artist_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
  <main>
    <div class="container mw-100">
      <div class="row" >
        <% @artists.each do |artist| %>
          <div class="card">
            <img src="<%= artist.image_url %>" class="card-img-top size_img" alt="<%= artist.name %>">
            <div class="card-body">
              <h5 class="card-title text-center"><%= artist.name %></h5>
              <%= link_to "Ver mas", artist_path(artist), class: "btn btn-primary btn-block" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </main>

app/views/artists/show.html.erb
<main>
  <div class="container mw-100">
    <div class="row">
      <div class="col-8 pull-content-star">
        <div class="p-5 mb-5">
          <h1> <%= @artist.name %> </h1>
          <h5>Albums (<%= @albums.length %>)</h5>
        </div>
        <div class="row">
          <% @albums.each do |album| %>
            <div class="card">
              <img src="<%= album.image_url %>" class="card-img-top" alt="<%= album.name %>">
              <div class="card-body">
                <h6> <%= album.name %> </h6>
                <p> <%= album.released_at %> </p>
              </div>
            </div>
          <% end %>
        </div>

      </div>
      <div class="col-4 p-5">
        <img src=" <%= @artist.image_url %>" class="rounded float-right" alt=" <%= @artist.name %> ">
      </div>

    </div>

  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySpotify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  class="bg-light">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark pr-5">
                    <a class="navbar-brand" href="#">Real Music</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <%= link_to "Artistas", artists_path, class: "nav-link" %>
                                <!-- <a class="nav-link" href="#">Artistas <span class="sr-only">(current)</span></a> -->
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Mi Musica <span class="sr-only">(current)</span></a>
                            </li>
                        </ul>
                        <div class="nav-bar justify-content-end">
                            <ul class="navbar-nav mr-auto">
                              <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Mi Cuenta
                                  </a>
                                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                      <a class="dropdown-item" href="#">Mi Perfil</a>
                                      <a class="dropdown-item" href="#">Mi Biblioteca</a>
                                      <div class="dropdown-divider"></div>
                                      <a class="dropdown-item" href="#">Configuración</a>
                                  </div>
                              </li>
                            </ul>
                        </div>
                    </div>
                </nav>
    </header>

    <%= yield %>
  </body>
</html>